set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4
syntax on

" highlight Comment ctermfg=lightblue

let g:netrw_liststyle=3 " Use tree-mode as default view
"let g:netrw_browse_split=4 " Open file in previous buffer
"let g:netrw_preview=1 " preview window shown in a vertically split
